### PR TITLE
Make into a true polyfill

### LINKED ISSUE #5: Become a "real" polyfill.
Basic steps:

- [x] Monkey patch `Ember.getOwner` when Ember version is too old
- [x] Deprecate usage of `import getOwner from 'ember-getowner-polyfill';`, in favor of just using `Ember.getOwner`
- [x] Bump major versions, remove deprecated `import` support.
- [ ] Work on common/top addons to update to latest version (ongoing)

### PR DESCRIPTION
**Pull request by ef4**
Partially addresses #5.

Why not patch in an initializer? Because then it wouldn't work in places like unit and integration tests.

### CODE REVIEW

**Comment by rwjblue** [comment]
> Why not patch in an initializer?

I *hate* initializers for this like a passion, would not merge 😝

**Comment by rwjblue** [comment]
We should avoid the `app.import` on ember versions that we know already have `Ember.getOwner`  / `Ember.setOwner`...

**Comment by rwjblue** [comment]
Followed up with the last part in https://github.com/rwjblue/ember-getowner-polyfill/pull/7

**Comment by ef4** [comment]
Oops, I think this may be firing the deprecation unnecessarily because of the way ember-load-initiailzers works.

**Comment by rwjblue** [comment]
> Oops, I think this may be firing the deprecation unnecessarily because of the way ember-load-initiailzers works.


ember-load-initializers should only require initializer files

**Comment by ef4** [comment]
Oh yes, I was seeing ember-concurrency's initializer, which does its own import of this polyfill, which is an appropriate use of the deprecation message.

**Pull request merged**
