### PR TITLE
package.json: Ensure to be included *before* ember-cli-shims 

### PR DESCRIPTION
**Pull request by Turbo87**
see https://embercommunity.slackarchive.io/dev-ember-cli/page-37/ts-1492609156178800 and below

as a bonus this PR also sorts the `package.json` file using https://github.com/keithamus/sort-package-json

### CODE REVIEW

**Comment by rwjblue** [comment]
> as a bonus this PR also sorts the package.json

O_o

**Comment by rwjblue** [comment]
LGTM, will merge + release when Travis is green...

**Comment by rwjblue** [comment]
ember-getowner-polyfill 1.2.3 published 🎉

**Comment by Turbo87** [comment]
muchas gracias

**Pull request merged**
